name: Build Custom Engine (Windows)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-windows-editor:
    runs-on: windows-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SCons
        run: python -m pip install --upgrade pip && pip install scons

      - name: Build Godot Windows editor (no C#)
        run: |
          scons platform=windows tools=yes target=release_debug -j%NUMBER_OF_PROCESSORS%
      
      - name: Upload built editor
        uses: actions/upload-artifact@v3
        with:
          name: custom-engine-windows
          path: bin/*.exe
